# language: node_js
# node_js:
#   - 12
# install:
#   - npm ci
# cache:
#   directories:
#     - "$HOME/.npm"
# script:
#   - npm test
# after_success:
#   - npm run update-data
#   - .travis/update-data.sh
#   - npm run build
# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   keep_history: true
#   local_dir: www/covid-19-dwt-analysis/
#   on:
#     branch: master
