language: node_js
node_js:
  - 12
install:
  - npm install
script:
  - npm run build
after_success:
  - .travis/update-data.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: www/
  on:
    branch: master
