/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Point, } from "./modules/data/data";
export namespace Components {
    interface AppRoot {
        /**
          * The wavelet coefficients.
         */
        "coeffs": number[][];
        /**
          * The interpolated time series data.
         */
        "interpTimeSeries": Point[];
        /**
          * The time series data.
         */
        "timeSeries": Point[];
    }
    interface PageDashboard {
        /**
          * Wavelet coefficients.
         */
        "coeffs": number[][];
        /**
          * Interpolated time series data.
         */
        "interpTimeSeries": Point[];
        /**
          * Time series data.
         */
        "timeSeries": Point[];
    }
    interface VegaVisualization {
        /**
          * Spacing in pixels to apply in order to fit plot exactly.
         */
        "spacing": number;
        /**
          * The specification of the visualization.
         */
        "spec": any;
    }
    interface VisualizationContainer {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPageDashboardElement extends Components.PageDashboard, HTMLStencilElement {
    }
    var HTMLPageDashboardElement: {
        prototype: HTMLPageDashboardElement;
        new (): HTMLPageDashboardElement;
    };
    interface HTMLVegaVisualizationElement extends Components.VegaVisualization, HTMLStencilElement {
    }
    var HTMLVegaVisualizationElement: {
        prototype: HTMLVegaVisualizationElement;
        new (): HTMLVegaVisualizationElement;
    };
    interface HTMLVisualizationContainerElement extends Components.VisualizationContainer, HTMLStencilElement {
    }
    var HTMLVisualizationContainerElement: {
        prototype: HTMLVisualizationContainerElement;
        new (): HTMLVisualizationContainerElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "page-dashboard": HTMLPageDashboardElement;
        "vega-visualization": HTMLVegaVisualizationElement;
        "visualization-container": HTMLVisualizationContainerElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
        /**
          * The wavelet coefficients.
         */
        "coeffs"?: number[][];
        /**
          * The interpolated time series data.
         */
        "interpTimeSeries"?: Point[];
        /**
          * The time series data.
         */
        "timeSeries"?: Point[];
    }
    interface PageDashboard {
        /**
          * Wavelet coefficients.
         */
        "coeffs"?: number[][];
        /**
          * Interpolated time series data.
         */
        "interpTimeSeries"?: Point[];
        /**
          * Time series data.
         */
        "timeSeries"?: Point[];
    }
    interface VegaVisualization {
        /**
          * Spacing in pixels to apply in order to fit plot exactly.
         */
        "spacing"?: number;
        /**
          * The specification of the visualization.
         */
        "spec"?: any;
    }
    interface VisualizationContainer {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "page-dashboard": PageDashboard;
        "vega-visualization": VegaVisualization;
        "visualization-container": VisualizationContainer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "page-dashboard": LocalJSX.PageDashboard & JSXBase.HTMLAttributes<HTMLPageDashboardElement>;
            "vega-visualization": LocalJSX.VegaVisualization & JSXBase.HTMLAttributes<HTMLVegaVisualizationElement>;
            "visualization-container": LocalJSX.VisualizationContainer & JSXBase.HTMLAttributes<HTMLVisualizationContainerElement>;
        }
    }
}
